/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WatchIndexRouteImport } from './routes/watch/index'
import { Route as WatchTrackIdRouteImport } from './routes/watch/$trackId'

const IndexLazyRouteImport = createFileRoute('/')()

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTrackIdRoute = WatchTrackIdRouteImport.update({
  id: '/watch/$trackId',
  path: '/watch/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/search': typeof SearchRoute
  '/watch/$trackId': typeof WatchTrackIdRoute
  '/watch/': typeof WatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/search': typeof SearchRoute
  '/watch/$trackId': typeof WatchTrackIdRoute
  '/watch': typeof WatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/search': typeof SearchRoute
  '/watch/$trackId': typeof WatchTrackIdRoute
  '/watch/': typeof WatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/watch/$trackId' | '/watch/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/watch/$trackId' | '/watch'
  id: '__root__' | '/' | '/search' | '/watch/$trackId' | '/watch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SearchRoute: typeof SearchRoute
  WatchTrackIdRoute: typeof WatchTrackIdRoute
  WatchIndexRoute: typeof WatchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$trackId': {
      id: '/watch/$trackId'
      path: '/watch/$trackId'
      fullPath: '/watch/$trackId'
      preLoaderRoute: typeof WatchTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SearchRoute: SearchRoute,
  WatchTrackIdRoute: WatchTrackIdRoute,
  WatchIndexRoute: WatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
